const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.LostTelegramMiniAppsSDK,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Dictionary,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.impactOccured,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.notificationOccurred,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.selectionChanged,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.UserPhotoUrl,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onWriteAccessCancelled,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.showAlert,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onWriteAccessAllowed,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onContactRequestSent,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onContactRequestCancelled,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onConfirmClosed,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onQrTextRecieved,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.closeScanQrPopup,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onScanQrPopupClosed,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.QrTextData,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.closeMiniApp,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.UserPremium,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.showConfirm,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.UserId,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.UserFirstName,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.UserLastName,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.UserUsername,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.UserLanguageCode,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.openLink,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.requestWriteAccess,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.requestContact,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.showScanQrPopup,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.shareToStory,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.requestFullscreen,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.exitFullscreen,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.addToHomeScreen,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onBMInited,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onBMAccessGranted,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onBMAccessDeclined,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onBMAuthenticatedSuccessfully,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onBMAuthenticateError,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.initBM,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.requestAccessBM,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.autheticateBM,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.openBMSettings,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.IsBiometricAvailable,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.IsBMAccessGranted,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.IsBMAccessRequested,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.BiometricToken,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.BiometricType,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.DeviceId,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onBackButtonClicked,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.showHideBackButton,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.showHideMainButton,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.enableDisableMainButton,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.enableDisableMainButtonShineEffect,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.showHideSecondaryButton,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.enableDisableSecondaryButton,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.enableDisableSecondaryButtonShineEffect,
		C3.ScriptsInEvents.Es_pages_Event68_Act1,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.setSecondaryButtonColor,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.setSecondaryButtonPosition,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onItemSet,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onItemSetError,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.setItem,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.removeItems,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.CloudStorageValue,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.LayerInteractive,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.NinePatch.Acts.SetEffectParam,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.setMainButtonText,
		C3.Plugins.LostTelegramMiniAppsSDK.Acts.setSecondaryButtonText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onSecondaryButtonClicked,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onMainButtonClicked,
		C3.Plugins.LostTelegramMiniAppsSDK.Exps.MainButtonText,
		C3.Plugins.LostTelegramMiniAppsSDK.Cnds.onViewportChanged,
		C3.Plugins.Browser.Acts.RequestFullScreen
	];
};
self.C3_JsPropNameTable = [
	{TelegramMiniApps: 0},
	{Browser: 0},
	{Id: 0},
	{ui_Text: 0},
	{Anchor: 0},
	{obj_Anchor: 0},
	{Class: 0},
	{InitialWidth: 0},
	{InitialHeight: 0},
	{COLOR_ID: 0},
	{ui_Button: 0},
	{Touch: 0},
	{Mouse: 0},
	{Colors: 0},
	{ui_TiledColor: 0},
	{ui_UserImage: 0},
	{IconGithub: 0},
	{Tween: 0},
	{Button: 0},
	{Text: 0},
	{CurrentPageIndex: 0},
	{PAGES_COUNT: 0},
	{LINK_CONSTRUCT: 0},
	{LINK_TG_CHANNEL: 0},
	{isPremium: 0},
	{isAvailable: 0},
	{isGranted: 0},
	{isRequested: 0},
	{randomColor: 0},
	{randomPosition: 0},
	{KEY_USERID: 0},
	{KEY_DATA: 0},
	{DEFAULT_COLOR: 0},
	{HOVER_COLOR: 0},
	{SizeReduceTime: 0},
	{SizeReducePercents: 0},
	{BUTTON_TEXT_PREVIOUS: 0},
	{BUTTON_TEXT_NEXT: 0},
	{BUTTON_TEXT_FINISH: 0}
];

self.InstanceType = {
	TelegramMiniApps: class extends self.C3.Plugins.LostTelegramMiniAppsSDK.Instance {},
	Browser: class extends self.IInstance {},
	ui_Text: class extends self.ITextInstance {},
	obj_Anchor: class extends self.ISpriteInstance {},
	ui_Button: class extends self.IWorldInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Colors: class extends self.IDictionaryInstance {},
	ui_TiledColor: class extends self.ITiledBackgroundInstance {},
	ui_UserImage: class extends self.ISpriteInstance {},
	IconGithub: class extends self.ISpriteInstance {},
	Button: class extends self.IWorldInstance {},
	Text: class extends self.ITextInstance {}
}